language: scala

jdk: openjdk8

scala:
   - 2.13.3

branches:
  only:
    - main

before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_8ebb1ef83f64_key 
    -iv $encrypted_8ebb1ef83f64_iv 
    -in github_deploy_key.enc 
    -out github_deploy_key 
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - git remote set-url origin git@github.com:marktoujiline/distributed-systems.git

stages:
  - name: test
    if: branch != main
  - name: release
    if: branch = main

jobs:
  include:
    - stage: test
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - stage: release
      script: git checkout -f main && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && sbt ++$TRAVIS_SCALA_VERSION "release with-defaults" # https://github.com/sbt/sbt-release/issues/210#issuecomment-340361000
