language: scala

jdk: openjdk8

scala:
   - 2.13.3

branches:
  only:
    - main

stages:
  - name: test
    if: branch != main
  - name: release
    if: branch = main

jobs:
  include:
    - stage: test
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - stage: release
      script: sbt ++$TRAVIS_SCALA_VERSION release
