name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt test

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - name: creds
      run: |
        git config --global user.name 'Mark Toujiline'
        git config --global user.email 'mark.toujiline@users.noreply.github.com'
    - name: Release
      run: sbt "release with-defaults"
